dist: trusty
language: go

go:
  - 1.8

install: true
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

before_script:
  - go get github.com/mattn/goveralls
  - sudo bash ./travis/setup-host
  - sudo lxc exec libvirt -- bash /code/travis/setup-guest

script:
  - sudo lxc exec libvirt -- bash /code/travis/run-tests-inside-guest
  - $HOME/gopath/bin/golint ./...
  - go vet -x
  - go test -v ./...
  - sudo lxc file pull libvirt/root/go/src/github.com/dmacvicar/terraform-provider-libvirt/profile.cov .
  - goveralls -coverprofile=profile.cov -service=travis-ci
